/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** TypeScript-friendly request object */
export interface Request {
  /** HTTP method (GET, POST, etc.) */
  method: string
  /** Full request path including query string */
  path: string
  /** Path without query string */
  pathOnly: string
  /** HTTP version */
  version: string
  /** Request headers as key-value pairs */
  headers: Record<string, string>
  /** Request body as UTF-8 string */
  body: string
  /** Route parameters (e.g., from "/users/:id") */
  params: Record<string, string>
  /** Query string parameters */
  query: Record<string, string>
  /** Request cookies */
  cookies: Record<string, string>
}
/** Static file serving options */
export interface StaticFileOptions {
  /** Enable directory listing */
  directoryListing?: boolean
  /** Cache control header */
  cacheControl?: string
  /** Custom headers */
  headers?: Record<string, string>
  /** Enable compression */
  compress?: boolean
}
/** Main Zap server class - ultra-fast HTTP server for Node.js */
export declare class Zap {
  /** Create a new Zap server instance */
  constructor()
  /** Set the server port */
  port(port: number): void
  /** Set the server hostname */
  hostname(hostname: string): void
  /** Set maximum request body size */
  maxRequestBodySize(size: number): void
  /** Enable CORS middleware */
  cors(): void
  /** Enable logging middleware */
  logging(): void
  /** Register a GET route with a simple string handler */
  get(path: string, handler: (...args: any[]) => any): void
  /** Register a GET route with an async handler */
  getAsync(path: string, handler: (...args: any[]) => any): void
  /** Register a GET route that returns JSON */
  getJson(path: string, handler: (...args: any[]) => any): void
  /** Register a POST route with an async handler */
  post(path: string, handler: (...args: any[]) => any): void
  /** Register a POST route that returns JSON */
  postJson(path: string, handler: (...args: any[]) => any): void
  /** Register a PUT route */
  put(path: string, handler: (...args: any[]) => any): void
  /** Register a DELETE route */
  delete(path: string, handler: (...args: any[]) => any): void
  /** Serve static files from a directory */
  staticFiles(prefix: string, directory: string, options?: StaticFileOptions | undefined | null): void
  /** Add a health check endpoint */
  healthCheck(path: string): void
  /** Add a metrics endpoint */
  metrics(path: string): void
  /** Start the server and listen for connections */
  listen(): Promise<void>
  /** Get server configuration info */
  getInfo(): string
}
export declare namespace utils {
  /** Parse JSON string to JavaScript object */
  export function parseJson(jsonStr: string): any
  /** Stringify JavaScript object to JSON */
  export function stringifyJson(value: any): string
  /** Get current timestamp in milliseconds */
  export function now(): number
}
