/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getVersion(): string
export declare class Router {
  constructor()
  register(method: string, path: string): HandlerId
  getHandlerId(method: string, path: string): HandlerId | null
}
export declare class Hooks {
  constructor()
  registerPreRouting(name: string): HookId
  registerPostHandler(name: string): HookId
  registerErrorHandler(name: string): HookId
  getPreRoutingHooks(): object
  getPostHandlerHooks(): object
  getErrorHandlerHooks(): object
  constructor()
  registerPreRouting(name: string): number
  registerPostHandler(name: string): number
  registerErrorHandler(name: string): number
  getPreRoutingHooks(): object
  getPostHandlerHooks(): object
  getErrorHandlerHooks(): object
}
